version: "3.9"

services:
  product_db:
    container_name: product_db
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
