version: "3.9"

networks:
  mynetwork:

services:
  product_db:
    container_name: product_db
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

  app:
    container_name: products_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: product_db
      DB_USER: postgres
      DB_PASSWORD: "1234"
      DB_NAME: postgres
      DB_PORT: "5432"
    ports:
      - "8080:8080"
    depends_on:
      - product_db
    networks:
      - mynetwork

volumes:
  pgdata: {}
